//$file${../::include::qm::qm_signals.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: main.qm
// File:  ${../::include::qm::qm_signals.h}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::include::qm::qm_signals.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __QM_SIGNALS_H__
#define __QM_SIGNALS_H__


#include "qpc.h"

enum qm_qpc_signals
{
    /*signal start value*/
    START_SIG = Q_USER_SIG,

    /*boot*/
    BOOT_TIMEOUT_SIG,
    BOOT_STRAP_SIG,

    /*activate AOs*/
    ACTIVATE_ACTOR_SIG,
    DEACTIVATE_ACTOR_SIG,

    /*app*/
    APP_ACTIVATE_SIG,
    APP_TIMEOUT_SIG,
    APP_NEXT_SIG,
    APP_START_SIG,
    APP_STOP_SIG,

    /*rtt*/
    RTT_TIMEOUT_SIG,
    RTT_INIT_SIG,
    RTT_DEINIT_SIG,

    /*led sig*/
    LED_TIMEOUT_SIG,
    LED_INIT_SIG,
    LED_DEINIT_SIG,
    LED_BLINK_SLOW_SIG,
    LED_BLINK_QUICK_SIG,

     /*kb*/
    KB_TIMEOUT_SIG,
    KB_INIT_SIG,
    KB_DEINIT_SIG,
    KB_HOLD_TIMEOUT_SIG,
    KB_KEY_EVENT_SIG,
    KB_K0_PRESS_SIG,
    KB_K0_RELEASE_SIG,
    KB_K1_PRESS_SIG,
    KB_K1_RELEASE_SIG,
    KB_K0_HOLD_SIG,
    KB_K1_HOLD_SIG,

    MAX_SIG,
};

#endif
