//$file${../::src::qm::qm_boot.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: boot.qm
// File:  ${../::src::qm::qm_boot.cpp}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::src::qm::qm_boot.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qm/qm_boot.h"
#include "qm/qm_common.h"

//$declare${base::qm_boot} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${base::qm_boot} ...........................................................
typedef struct {
// protected:
    QActive super;

// public:
    QTimeEvt timer;
    QTimeEvt alart_timer;
} qm_boot;

// protected:
static QState qm_boot_initial(qm_boot * const me, void const * const par);
static QState qm_boot_init(qm_boot * const me, QEvt const * const e);
static QState qm_boot_reset(qm_boot * const me, QEvt const * const e);
//$enddecl${base::qm_boot} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


static qm_boot l_qm_boot;

QActive* const ao_qm_boot = (QActive*)&l_qm_boot;

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${base::qm_boot_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${base::qm_boot_ctor} ......................................................
void qm_boot_ctor(void) {
    qm_boot *me = &l_qm_boot;

    QActive_ctor(&me->super, Q_STATE_CAST(&qm_boot_initial));

    QTimeEvt_ctorX (&me->timer, &me->super, BOOT_TIMEOUT_SIG, 0U);

}
//$enddef${base::qm_boot_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${base::qm_boot} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${base::qm_boot} ...........................................................

//${base::qm_boot::SM} .......................................................
static QState qm_boot_initial(qm_boot * const me, void const * const par) {
    //${base::qm_boot::SM::initial}
    QActive_subscribe((QActive *)me, BOOT_STRAP_SIG);
    return Q_TRAN(&qm_boot_reset);
}

//${base::qm_boot::SM::init} .................................................
static QState qm_boot_init(qm_boot * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${base::qm_boot::SM::init}
        case Q_ENTRY_SIG: {
            LOG("qm_boot init");

            {
            QEvt *pe = Q_NEW(QEvt, APP_ACTIVATE_SIG);
            QF_PUBLISH((QEvt*)pe, NULL);
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${base::qm_boot::SM::reset} ................................................
static QState qm_boot_reset(qm_boot * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${base::qm_boot::SM::reset}
        case Q_ENTRY_SIG: {
            LOG("qm_boot reset");



            status_ = Q_HANDLED();
            break;
        }
        //${base::qm_boot::SM::reset}
        case Q_EXIT_SIG: {
            //LOG("core bootstrap");
            status_ = Q_HANDLED();
            break;
        }
        //${base::qm_boot::SM::reset::BOOT_STRAP}
        case BOOT_STRAP_SIG: {
            LOG("BOOT_STRAP_SIG");
            status_ = Q_TRAN(&qm_boot_init);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${base::qm_boot} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

