//$file${../::src::qm::qm_rtt.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: rtt.qm
// File:  ${../::src::qm::qm_rtt.cpp}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::src::qm::qm_rtt.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qm/qm_rtt.h"
#include "qm/qm_common.h"

//$declare${base::qm_rtt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${base::qm_rtt} ............................................................
typedef struct {
// protected:
    QActive super;

// public:
    QTimeEvt timer;
} qm_rtt;

// protected:
static QState qm_rtt_initial(qm_rtt * const me, void const * const par);
static QState qm_rtt_active(qm_rtt * const me, QEvt const * const e);
static QState qm_rtt_reset(qm_rtt * const me, QEvt const * const e);
//$enddecl${base::qm_rtt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


static qm_rtt l_qm_rtt;

QActive* const ao_qm_rtt = (QActive*)&l_qm_rtt;

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${base::qm_rtt_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${base::qm_rtt_ctor} .......................................................
void qm_rtt_ctor(void) {
    qm_rtt *me = &l_qm_rtt;

    QActive_ctor(&me->super, Q_STATE_CAST(&qm_rtt_initial));

    QTimeEvt_ctorX (&me->timer, &me->super, RTT_TIMEOUT_SIG, 0U);

}
//$enddef${base::qm_rtt_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${base::qm_rtt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${base::qm_rtt} ............................................................

//${base::qm_rtt::SM} ........................................................
static QState qm_rtt_initial(qm_rtt * const me, void const * const par) {
    //${base::qm_rtt::SM::initial}
    QActive_subscribe((QActive *)me, ACTIVATE_ACTOR_SIG);
    QActive_subscribe((QActive *)me, DEACTIVATE_ACTOR_SIG);
    return Q_TRAN(&qm_rtt_reset);
}

//${base::qm_rtt::SM::active} ................................................
static QState qm_rtt_active(qm_rtt * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${base::qm_rtt::SM::active}
        case Q_ENTRY_SIG: {
            LOG("qm_rtt active");

            QTimeEvt_armX(&me->timer,  BSP_TICKS_PER_SEC, BSP_TICKS_PER_SEC/5);
            status_ = Q_HANDLED();
            break;
        }
        //${base::qm_rtt::SM::active::RTT_TIMEOUT}
        case RTT_TIMEOUT_SIG: {

            rtt_poll();

            status_ = Q_HANDLED();
            break;
        }
        //${base::qm_rtt::SM::active::DEACTIVATE_ACTOR}
        case DEACTIVATE_ACTOR_SIG: {
            status_ = Q_TRAN(&qm_rtt_reset);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${base::qm_rtt::SM::reset} .................................................
static QState qm_rtt_reset(qm_rtt * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${base::qm_rtt::SM::reset}
        case Q_ENTRY_SIG: {
            LOG("qm_rtt reset");
            status_ = Q_HANDLED();
            break;
        }
        //${base::qm_rtt::SM::reset::ACTIVATE_ACTOR}
        case ACTIVATE_ACTOR_SIG: {
            status_ = Q_TRAN(&qm_rtt_active);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${base::qm_rtt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

